version: "2"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python application.py"
    volumes:
      - ./api:/api
    environment:
      - PYTHONPATH=/api
      - PYTHONDONTWRITEBYTECODE=0
    ports:
      - "5000:5000"
